'''
We referred to a couple of prompting templates for the BUSI dataset to make our custom 24 prompt ... editing the generate prompt templates generated by Azure GPT-5.4.
See: https://github.com/pengwei222/Biomed-DPT/blob/main/trainers/prompt_templates.py
See: https://github.com/HealthX-Lab/BiomedCoOp/blob/main/trainers/prompt_templates.py
'''

PROMPT_REGISTRY = {
    'benign tumor': [
        'a grayscale breast ultrasound image showing a benign breast mass.',
        'a grayscale breast ultrasound image showing a benign breast lesion.',
        'a breast ultrasound image showing an oval benign breast mass.',
        'a breast ultrasound image showing a benign breast mass with circumscribed margins.',
        'a breast ultrasound image showing a benign breast mass with parallel orientation.',
        'a grayscale breast ultrasound image showing a hypoechoic benign breast mass.',
        'a breast ultrasound image showing an oval benign breast mass with circumscribed margins.',
        'a breast ultrasound image showing an oval benign breast mass with parallel orientation.',
        'a breast ultrasound image showing a circumscribed benign breast mass with parallel orientation.',
        'a breast ultrasound image showing an oval, circumscribed, parallel-oriented benign breast mass.',
        'a breast ultrasound image showing a wider-than-tall benign breast mass with circumscribed margins.',
        'a grayscale breast ultrasound image showing a homogeneous hypoechoic benign breast mass.',
        'a grayscale breast ultrasound image showing a circumscribed hypoechoic benign breast mass.',
        'a breast ultrasound image showing an oval hypoechoic benign breast mass with circumscribed margins.',
        'a breast ultrasound image showing a homogeneous hypoechoic benign breast mass with parallel orientation.',
        'a breast ultrasound image showing an oval, hypoechoic, circumscribed benign breast mass with parallel orientation.',
        'a breast ultrasound image showing a benign breast mass with no posterior acoustic features.',
        'a breast ultrasound image showing a benign breast mass with posterior acoustic enhancement.',
        'a breast ultrasound image showing a round or oval anechoic benign breast lesion with circumscribed margins.',
        'a breast ultrasound image showing an anechoic circumscribed benign breast lesion with posterior acoustic enhancement.',
        'a breast ultrasound image showing an oval cystic benign breast lesion with a thin wall and posterior acoustic enhancement.',
        'a breast ultrasound image showing a circumscribed benign breast mass with a thin echogenic pseudocapsule.',
        'a breast ultrasound image showing a well-defined benign breast lesion without architectural distortion.',
        'a grayscale breast ultrasound image showing an oval benign lesion with circumscribed margins, parallel orientation, and homogeneous internal echoes.'
    ],

    'malignant tumor': [
        'a grayscale breast ultrasound image showing a malignant breast mass.',
        'a grayscale breast ultrasound image showing a malignant breast lesion.',
        'a breast ultrasound image showing an irregular malignant breast mass.',
        'a breast ultrasound image showing a malignant breast mass with non-circumscribed margins.',
        'a breast ultrasound image showing a malignant breast mass with non-parallel orientation.',
        'a grayscale breast ultrasound image showing a hypoechoic malignant breast mass.',
        'a breast ultrasound image showing an irregular malignant breast mass with non-circumscribed margins.',
        'a breast ultrasound image showing an irregular malignant breast mass with non-parallel orientation.',
        'a breast ultrasound image showing a non-circumscribed malignant breast mass with non-parallel orientation.',
        'a breast ultrasound image showing an irregular, non-circumscribed, non-parallel malignant breast mass.',
        'a breast ultrasound image showing a taller-than-wide malignant breast mass with non-circumscribed margins.',
        'a grayscale breast ultrasound image showing a heterogeneous hypoechoic malignant breast mass.',
        'a breast ultrasound image showing a hypoechoic malignant breast mass with indistinct margins.',
        'a breast ultrasound image showing an irregular malignant breast mass with angular margins.',
        'a breast ultrasound image showing an irregular malignant breast mass with microlobulated margins.',
        'a breast ultrasound image showing an irregular malignant breast mass with spiculated margins.',
        'a breast ultrasound image showing a malignant breast mass with posterior acoustic shadowing.',
        'a breast ultrasound image showing an irregular malignant breast mass with posterior acoustic shadowing.',
        'a breast ultrasound image showing an irregular hypoechoic malignant breast mass with non-circumscribed margins and posterior acoustic shadowing.',
        'a breast ultrasound image showing a malignant breast mass with irregular margins and architectural distortion.',
        'a breast ultrasound image showing an irregular malignant breast lesion with disruption of surrounding tissue planes.',
        'a breast ultrasound image showing a malignant breast mass with a thick echogenic rind.',
        'a breast ultrasound image showing an irregular malignant breast mass with spiculated margins and architectural distortion.',
        'a grayscale breast ultrasound image showing an irregular, hypoechoic, non-parallel malignant mass with non-circumscribed margins and posterior acoustic shadowing.'
    ],

    'normal scan': [
        'a normal grayscale breast ultrasound image.',
        'a grayscale breast ultrasound image showing normal breast tissue.',
        'a breast ultrasound image showing normal breast parenchyma.',
        'a breast ultrasound image showing a normal sonographic breast appearance.',
        'a breast ultrasound image showing normal breast tissue without a mass.',
        'a breast ultrasound image showing normal breast tissue without a lesion.',
        'a breast ultrasound image showing normal breast tissue without a focal abnormality.',
        'a breast ultrasound image showing normal breast tissue without a suspicious finding.',
        'a breast ultrasound image showing no visible breast lesion.',
        'a breast ultrasound image showing no discrete breast mass.',
        'a breast ultrasound image showing no focal breast mass.',
        'a breast ultrasound image showing no suspicious breast mass.',
        'a breast ultrasound image showing normal background breast echotexture without a focal lesion.',
        'a breast ultrasound image showing homogeneous background echotexture without a focal lesion.',
        'a breast ultrasound image showing homogeneous fibroglandular background echotexture without a focal lesion.',
        'a breast ultrasound image showing homogeneous fatty background echotexture without a focal lesion.',
        'a breast ultrasound image showing heterogeneous background echotexture without a focal lesion.',
        'a breast ultrasound image showing normal breast parenchyma without a hypoechoic mass.',
        'a breast ultrasound image showing normal tissue planes without a visible lesion.',
        'a breast ultrasound image showing preserved normal breast tissue planes without a focal lesion.',
        'a breast ultrasound image showing no architectural distortion or discrete breast mass.',
        'a breast ultrasound image showing no suspicious mass or distortion of the normal breast parenchyma.',
        'a breast ultrasound image showing no solid or cystic focal breast lesion.',
        'a grayscale breast ultrasound image showing normal breast tissue with no identifiable mass, focal lesion, or architectural distortion.'
    ]
}